### ISSUE TITLE
How to traverse a graph to g1 and feat1？

### ISSUE THREAD

**Issue by c464851257** [luleg/WeisfeilerLehmanKernel#1]
Thanks for sharing this code. 
If i want to transform a graph to g1 and feat1, what should i do.

**Comment by luleg** [comment]
You're welcome.
Could you specify what you mean by g1 and feat1?
If you refer to the readme, what I call g1 and feat1 refer to the graph attached (screen shot from [https://www.jmlr.org/papers/volume12/shervashidze11a/shervashidze11a.pdf](https://www.jmlr.org/papers/volume12/shervashidze11a/shervashidze11a.pdf)), where node features are given inside the nodes. If you draw the graph whose edges are in Data/g1.txt and node features in Data/feat1.txt, you end with the graph attached.
<img width="91" alt="Screenshot 2022-09-14 103402" src="https://user-images.githubusercontent.com/46683383/190118557-e5b6b998-c0a4-4903-bd7c-3cfbbdedef88.png">

**Comment by c464851257** [comment]
> 

Thanks reply.
What I mean is how to convert graph into data in this format(like g1 and feat1), are there any rules? It doesn't seem to be mentioned in the paper.

**Comment by luleg** [comment]
Graphs must be given as a weighted edgelist. If your graph is stored in another format, you may use [networkx functions](https://networkx.org/documentation/stable/reference/readwrite/index.html) for this. For the features, that's a two column file with node's identifier on the left column and node's feature (must be an integer) on the right. You need to build it by yourself. Note that it is not required to povide those features. These are optional, and if not provided, nodes' degrees are used as features, as specified in the readme.

**Comment by c464851257** [comment]
> 

Got it.
Thank you so much.
